### ISSUE TITLE
[Feature proposal]: Reuse same color for multiple labels

### ISSUE THREAD

**Issue by saroad2** [hackebrot/labels#22]
Consider the following *labels.toml* file:
```toml
[bug]
color = "dd2525"
name = "bug"
description = "A confirmed crash or error in behavior."

[documentation]
color = "8125dd"
name = "documentation"
description = "The issue relates to documentation."

[duplicate]
color = "333333"
name = "duplicate"
description = "A duplicate of an existing ticket."

[linux]
color = "25d4dd"  # platform label
name = "linux"
description = "The issue relates Linux support."

[macOS]
color = "25d4dd"  # platform label
name = "macOS"
description = "The issue relates to Apple macOS support."

[windows]
color = "25d4dd"  # platform label
name = "windows"
description = "The issue relates to Microsoft Windows support."
```

As you can see, some of the platforms have the same color intentionally. This is due to the reason that they represent the same type of label. It would be nice if once could do the following:

```toml
[colors]
platform = "25d4dd"

[bug]
color = "dd2525"
name = "bug"
description = "A confirmed crash or error in behavior."

[documentation]
color = "8125dd"
name = "documentation"
description = "The issue relates to documentation."

[duplicate]
color = "333333"
name = "duplicate"
description = "A duplicate of an existing ticket."

[linux]
color = "platform"
name = "linux"
description = "The issue relates Linux support."

[macOS]
color = "platform"
name = "macOS"
description = "The issue relates to Apple macOS support."

[windows]
color = "platform"
name = "windows"
description = "The issue relates to Microsoft Windows support."
```

What do you think? Once you approve, I will implement it.
